name: yss_todo
description: A new Flutter project.
publish_to: 'none'
version: 0.4.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  build_runner: ^2.4.5
  device_info_plus: ^9.0.2
  equatable: ^2.0.5
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  get_it: ^7.6.0
  get_storage: ^2.1.1
  http: ^1.0.0
  intl: ^0.18.0
  logger: ^1.4.0
  mobx: ^2.2.0
  mockito: ^5.4.2
  slang: ^3.18.1
  slang_flutter: ^3.18.0
  uuid: ^3.0.7

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_annotation: ^4.8.1
  json_serializable_mobx: ^0.10.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/