name: Android build normal
 
on:
  workflow_dispatch:
jobs:
  build:
    name: Build android on Mac OS
    runs-on: macos-11
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
 
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta
      - name: Set up JDK 11
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          java-version: 11
          distribution: temurin
          
      - name: Firebase options create
        run: touch ./lib/firebase_options.dart
        
      - name: Firebase options update
        env:
          FIREBASE_OPTIONS: ${{secrets.FIREBASE_OPTIONS}}
        run: |
          echo $FIREBASE_OPTIONS > ./lib/firebase_options.dart
      
      - name: Create google-services.json file
        run: touch ./android/app/google-services.json
        
      - name: Set up google-services.json file
        env:
          GOOGLE_SERVICES_ANDROID: ${{ secrets.GOOGLE_SERVICES_ANDROID }}
        run: |
          echo $GOOGLE_SERVICES_ANDROID > ./android/app/google-services.json
      
      - run: flutter pub get
      - run: flutter build apk --dart-define HOST= ${{ secrets.HOST }} --dart-define TOKEN= ${{ secrets.TOKEN }} --flavor normal --target lib/main.dart
      - run: flutter build apk --split-per-abi --dart-define HOST= ${{ secrets.HOST }} --dart-define TOKEN= ${{ secrets.TOKEN }} --flavor normal --target lib/main.dart

      - uses: actions/upload-artifact@v3
        with:
          name: arm-v8a
          path: build/app/outputs/flutter-apk
