name: Android build normal

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.workspace }}
    - run: touch ./android/app/google-services.json
    - run: echo ${{secrets.GOOGLE_SERVICES_ANDROID}} > ./android/app/google-services.json

    - name: Firebase config
      run: touch ./lib/firebase_options.dart
    
    - env:
        OPTIONS: ${{secrets.FIREBASE_OPTIONS}}
      run: |
        echo $OPTIONS > ./lib/firebase_options.dart


    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: "beta"
        cache: true
    - run: flutter pub get
    - run: flutter build apk --dart-define HOST= ${{ secrets.HOST }} --dart-define TOKEN= ${{ secrets.TOKEN }} --flavor normal --target lib/main.dart
    - run: flutter build apk --split-per-abi --dart-define HOST= ${{ secrets.HOST }} --dart-define TOKEN= ${{ secrets.TOKEN }} --flavor normal --target lib/main.dart

    - uses: actions/upload-artifact@v3
      with:
        name: arm-v8a
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
        
#     - name: send to telegram
#       uses: appleboy/telegram-action@master
#       with:
#         to: ${{ secrets.TELEGRAM_TO }}
#         token: ${{ secrets.TELEGRAM_TOKEN }}
#         message: flutter release armv7
#         document: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
#     - uses: appleboy/telegram-action@master
#       with:
#         to: ${{ secrets.TELEGRAM_TO }}
#         token: ${{ secrets.TELEGRAM_TOKEN }}
#         message: flutter release armv8
#         document: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
#     - uses: appleboy/telegram-action@master
#       with:
#         to: ${{ secrets.TELEGRAM_TO }}
#         token: ${{ secrets.TELEGRAM_TOKEN }}
#         message: flutter release universal
#         document: build/app/outputs/flutter-apk/app-release.apk   


